#version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: drscam
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: alimentation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app
      FLASK_ENV: development

volumes:
  postgres_data:
